### ISSUE TITLE
Disable steamlug-bot on queries that SteamDB's bot deals with

### ISSUE THREAD

**Issue by tYGjQCsvVI** [SteamLUG/steamlug-bot#4]
Linking to a Steam store page in \#SteamLUG results in two bots replying to you, with SteamDB's bot doing a better job (Including pricing and replies faster).

steamlug-bot needs to be disabled for those items.

**Comment by EndeavourAccuracy** [comment]
I agree this needs a solution.

It would be a simple code change to have just the SteamDB bot do this, but this may not be the best solution for the reasons described below.

While the SteamDB bot replies 3-4 seconds faster, it occasionally gives the wrong pricing information. Not only does it currently not take into account that there are two Euro regions...

Example:
> psymin: http://store.steampowered.com/app/17710/\
> SteamDB: » App 17710 — Nuclear Dawn (8,99€ / £6.99 / $9.99)
> steamlug-bot: [url] Nuclear Dawn on Steam (now €9,99(t1)/€8,99(t2)/£6.99/US$9.99)

...with the tier 1 ("t1") being the one that, for example, I live in, but because it doesn't retrieve rates in real-time it may also give inaccurate pricing information right after sales kick in - which is exactly when people link to games.

Euro still needs updating here, for example:
> steamlug-bot: [new] Alarameth TD™ http://store.steampowered.com/app/377280/ (now €5,59/£3.99/US$5.59)
> SteamDB: » App 377280 — Alarameth TD (Alarameth TD™) (6,99€ / £3.99 at -20% / $5.59 at -20%)

It is also more frequently than steamlug-bot not reacting to URLs at all. I don't know why it's not. Maybe there are periods when the bot is disabled, maybe it doesn't recognize certain URLs, maybe it's not in the channel.

Example:
> psymin: Free copy of this game if anyone wants it: http://store.steampowered.com/app/347240/
> steamlug-bot: [url] Save 50% on Challenge of the Five Realms: Spellbound in the World of Nhagardia on Steam (now €3,49/£2.49/US$3.49)
> Evropi: apo_: up for a trade today? :D:D
(etc.)

If just the SteamDB bot would do this task, @xPaw would have to look into these things. It also does not make sense that the SteamDB bot reacts to steamlug-bot, especially when it reacts to steamlug-bot's "[new]" lines - since it brings nothing new to the table.

Also, as you can see in the examples above, steamlug-bot *does* in fact include pricing information. When there are instances when it does not, my opinion is that this needs either a bug report in Valve's direction about their API, or the steamlug-bot code that accesses the API needs to be improved.

And, for consistency's sake, it may be better to disable the replies of the SteamDB bot in #steamlug, even though it is some seconds faster.

Finally, I think it would be best if xPaw would consult with both me and with the SteamLUG community group owners/officers and IRC channel operators before introducing features that steamlug-bot either already takes care of or easily can take care of. Two examples:

1. Out of the blue, the SteamDB bot started reacting to Steam store URLs, even though steamlug-bot was already doing this. Yes, that's right, steamlug-bot *was already doing this*, but suddenly someone decided that the SteamDB bot had to also spam the channel. No consultation, no discussions, nothing. At the time, steamlug-bot did not include pricing information, but in May I added code for this. See https://github.com/SteamLUG/steamlug-bot/commit/2dcd477e0df43cb1f97919f8d7c85e2813501ed7 and also https://github.com/SteamLUG/steamlug-bot/commit/83fe05eb8278f9b40e75c2d959aec3553fbc029e

2. Out of the blue, the SteamDB bot started reacting to Twitter URLs. Again, no consultation, no discussions, nothing. And this was when steamlug-bot already had functionality to retrieve and display Tweets (with "!t"). In May I added code that made it also react to URLs. See https://github.com/SteamLUG/steamlug-bot/commit/d101af37457a73855ccc48d46cb45814723e5ca8

There has been a lack of communication from the SteamDB bot owner(s) side that also became apparent in other instances. For example, after the steamstat.us API changed, I was not notified about this and found out days later that steamlug-bot's "!steamstatus" had broken because of the change. I fixed this in March. See https://github.com/SteamLUG/steamlug-bot/commit/86c1799f6a95ff103c3e09d7e636322acee60518

And when I asked for information, this is what happened:

> norbert: xPaw: hm, did steamstat.us change?
> xPaw: does it look different to you

Maybe that's miscommunication, but to me that looks like a cryptic, rhetorical answer either way. And it's not the first one I've gotten from xPaw. I remember when the API link was removed from steamstat.us and I asked what the new URL was, I ended up studying the HTML source code to find out myself. Maybe things went wrong in April 2014, when I felt that xPaw kept (telling me how bad PHP was and kept) trying to make steamlug-bot's "!s" misbehave/fail and bug other people to a point where I felt I had to put xPaw in the ignore list. See https://github.com/SteamLUG/steamlug-bot/commit/634b198b16ec1f009332d7e2cf92d6d8e35059ba Unignored since https://github.com/SteamLUG/steamlug-bot/commit/42f6ca9ec5c4303d74e97c6df7ad051104513a19

I'm not sure if the SteamDB bot's faster replies are a good enough reason to disable the steamlug-bot feature. Why not disable the SteamDB bot's feature instead and improve steamlug-bot where necessary. What if, hypothetically, another bot would join the channel and out of the blue would start giving information about YouTube URLs as steamlug-bot does, but this new bot would also include the number of views. Does this mean we need to disable the steamlug-bot feature? Or should we tell that bot owner: that's nice, but as you can see we already have a bot that replies to such URLs and if you want it to include the number of views, maybe communicate with that bot's author and with us first.

And, for the record, I (too) can be difficult to communicate with. I can be quite stubborn, for example. I'm far from perfect. My code also isn't perfect.

I haven't made any code changes yet.
I'm leaving this issue open so other people can comment on your request.

**Comment by xPaw** [comment]
You have to realise that SteamDB bot is in other channels as well.

>  Out of the blue, the SteamDB bot started reacting to Twitter URLs.

That was a different bot, Wendy. And unless I'm mistaken, it no longer does
YT/twitter in steamlug.

>

I remember when the API link was removed from steamstat.us and I asked what
the new URL was, I ended up studying the HTML source code to find out
myself.

You don't seem to understand that this API is meant for our internal use
only. It can break at any time, it is not versioned, there are no
guarantees.


On Tue, 30 Jun 2015 10:32 EndeavourAccuracy <notifications@github.com>
wrote:

I agree this needs a solution.

It would be a simple code change to have just the SteamDB bot do this, but
this may not be the best solution for the reasons described below.

While the SteamDB bot replies 3-4 seconds faster, it occasionally gives the
wrong pricing information. Not only does it currently not take into account
that there are two Euro regions...

Example:

psymin: http://store.steampowered.com/app/17710/\
SteamDB: » App 17710 — Nuclear Dawn (8,99€ / £6.99 / $9.99)
steamlug-bot: [url] Nuclear Dawn on Steam (now
€9,99(t1)/€8,99(t2)/£6.99/US$9.99)


...with the tier 1 ("t1") being the one that, for example, I live in, but
because it doesn't retrieve rates in real-time it may also give inaccurate
pricing information right after sales kick in - which is exactly when
people link to games.

Euro still needs updating here, for example:

steamlug-bot: [new] Alarameth TD™ http://store.steampowered.com/app/377280/
(now €5,59/£3.99/US$5.59)
SteamDB: » App 377280 — Alarameth TD (Alarameth TD™) (6,99€ / £3.99 at -20%
/ $5.59 at -20%)


It is also more frequently than steamlug-bot not reacting to URLs at all. I
don't know why it's not. Maybe there are periods when the bot is disabled,
maybe it doesn't recognize certain URLs, maybe it's not in the channel.

Example:

psymin: Free copy of this game if anyone wants it:
http://store.steampowered.com/app/347240/
steamlug-bot: [url] Save 50% on Challenge of the Five Realms: Spellbound in
the World of Nhagardia on Steam (now €3,49/£2.49/US$3.49)
Evropi: apo_: up for a trade today? :D:D
(etc.)


If just the SteamDB bot would do this task, @xPaw <https://github.com/xPaw>
would have to look into these things. It also does not make sense that the
SteamDB bot reacts to steamlug-bot, especially when it reacts to
steamlug-bot's "[new]" lines - since it brings nothing new to the table.

Also, as you can see in the examples above, steamlug-bot *does* in fact
include pricing information. When there are instances when it does not, my
opinion is that this needs either a bug report in Valve's direction about
their API, or the steamlug-bot code that accesses the API needs to be
improved.

And, for consistency's sake, it may be better to disable the replies of the
SteamDB bot in #steamlug, even though it is some seconds faster.

Finally, I think it would be best if xPaw would consult with both me and
with the SteamLUG community group owners/officers and IRC channel operators
before introducing features that steamlug-bot either already takes care of
or easily can take care of. Two examples:

Out of the blue, the SteamDB bot started reacting to Steam store URLs, even
though steamlug-bot was already doing this. Yes, that's right,
steamlug-bot *was
already doing this*, but suddenly someone decided that the SteamDB bot had
to also spam the channel. No consultation, no discussions, nothing. At the
time, steamlug-bot did not include pricing information, but in May I added
code for this. See 2dcd477
<https://github.com/SteamLUG/steamlug-bot/commit/2dcd477e0df43cb1f97919f8d7c85e2813501ed7>
and also 83fe05e
<https://github.com/SteamLUG/steamlug-bot/commit/83fe05eb8278f9b40e75c2d959aec3553fbc029e>

Out of the blue, the SteamDB bot started reacting to Twitter URLs. Again,
no consultation, no discussions, nothing. And this was when steamlug-bot
already had functionality to retrieve and display Tweets (with "!t"). In
May I added code that made it also react to URLs. See d101af3
<https://github.com/SteamLUG/steamlug-bot/commit/d101af37457a73855ccc48d46cb45814723e5ca8>

There has been a lack of communication from the SteamDB bot owner(s) side
that also became apparent in other instances. For example, after the
steamstat.us API changed, I was not notified about this and found out days
later that steamlug-bot's "!steamstatus" had broken because of the change.
I fixed this in March. See 86c1799
<https://github.com/SteamLUG/steamlug-bot/commit/86c1799f6a95ff103c3e09d7e636322acee60518>

And when I asked for information, this is what happened:

norbert: xPaw: hm, did steamstat.us change?
xPaw: does it look different to you


Maybe that's miscommunication, but to me that looks like a cryptic,
rhetorical answer either way. And it's not the first one I've gotten from
xPaw. I remember when the API link was removed from steamstat.us and I
asked what the new URL was, I ended up studying the HTML source code to
find out myself. Maybe things went wrong in April 2014, when I felt that
xPaw kept (telling me how bad PHP was and kept) trying to make
steamlug-bot's "!s" misbehave/fail and bug other people to a point where I
felt I had to put xPaw in the ignore list. See 634b198
<https://github.com/SteamLUG/steamlug-bot/commit/634b198b16ec1f009332d7e2cf92d6d8e35059ba>
Unignored since 42f6ca9
<https://github.com/SteamLUG/steamlug-bot/commit/42f6ca9ec5c4303d74e97c6df7ad051104513a19>

I'm not sure if the SteamDB bot's faster replies are a good enough reason
to disable the steamlug-bot feature. Why not disable the SteamDB bot's
feature instead and improve steamlug-bot where necessary. What if,
hypothetically, another bot would join the channel and out of the blue
would start giving information about YouTube URLs as steamlug-bot does, but
this new bot would also include the number of views. Does this mean we need
to disable the steamlug-bot feature? Or should we tell that bot owner:
that's nice, but as you can see we already have a bot that replies to such
URLs and if you want it to include the number of views, maybe communicate
with that bot's author and with us first.

And, for the record, I (too) can be difficult to communicate with. I can be
quite stubborn, for example. I'm far from perfect. My code also isn't
perfect.

I haven't made any code changes yet.
I'm leaving this issue open so other people can comment on your request.

—
Reply to this email directly or view it on GitHub
<https://github.com/SteamLUG/steamlug-bot/issues/4#issuecomment-117037616>.<img
src="
https://ci3.googleusercontent.com/proxy/03dMBl8jfnlIJYD0_OMMZgPPHqZp5cIfIdCnQ1KxD11HjA9-lR8fCSBo-RmqyijXjm1VlhfXYEpA95jRrCXNUwbU5--u0hLayyrn2L-hop6ShlkTE3EO3r5HY_FjfjjYLZ1bFMcX0ZhZYXwICRvS6c96cU5n8Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAlb0zsWLmgHwShoT8-eWYievSu-8z46ks5oYj2bgaJpZM4FOX4f.gif
">

**Comment by johndrinkwater** [comment]
We're always going to have both the bots in the channel, as one supports our events and steamid management, and the other does update tracking and supports querying active players.

For now I would prefer disabling the feature in our steamlug-bot, and revisit it in future if things change.
There are going to be some new things for our bot to do soon, so it shouldn't seem like we are backing off from having an important digital buddy in our channel ;)

**Comment by EndeavourAccuracy** [comment]
Alrighty, disabled. https://github.com/SteamLUG/steamlug-bot/commit/bc03ab28c637b35b431ba48fe24140d0023aea3e
